
/*  ************************************************************************  *
 *				    common.h				      *
 *  ************************************************************************  */

/*  This header contains everything that every source file will include
    first and every include file may take for granted as being already
    included.  */

/*  ************************************************************************  */

#pragma     once

#define     UNICODE
#define     WIN32_LEAN_AND_MEAN
#define     _WIN32_WINNT    0x0501
#include    <windows.h>

/*  A few things the author happens to like  */

#define     AND &&
#define     NOT !
#define     OR	||

/*  ************************************************************************  */

